// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjtMn6BEEFhgvTRcXS6lJfBe1iBLzhcc',
    appId: '1:593069841441:web:1a17597890831211365760',
    messagingSenderId: '593069841441',
    projectId: 'fir-database-d5e3f',
    authDomain: 'fir-database-d5e3f.firebaseapp.com',
    storageBucket: 'fir-database-d5e3f.appspot.com',
    measurementId: 'G-N4QM73W5CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBncS_cJHzPlYAxo3rLzT4BK8wDkxWDhQ',
    appId: '1:593069841441:android:ac0dfdae0a807bb7365760',
    messagingSenderId: '593069841441',
    projectId: 'fir-database-d5e3f',
    storageBucket: 'fir-database-d5e3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5UF9zKzl3AfpMXTXRa7ufrPkq4CqZKnM',
    appId: '1:593069841441:ios:32d88afa5850c60a365760',
    messagingSenderId: '593069841441',
    projectId: 'fir-database-d5e3f',
    storageBucket: 'fir-database-d5e3f.appspot.com',
    iosBundleId: 'com.example.flutterDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5UF9zKzl3AfpMXTXRa7ufrPkq4CqZKnM',
    appId: '1:593069841441:ios:dc46cc4cb891e463365760',
    messagingSenderId: '593069841441',
    projectId: 'fir-database-d5e3f',
    storageBucket: 'fir-database-d5e3f.appspot.com',
    iosBundleId: 'com.example.flutterDb.RunnerTests',
  );
}
