///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MoviesModel {
// {
//   "thumnail": "datas",
//   "title": "movie title",
//   "subtitle": "hello subtitle",
//   "contents": "hello world",
//   "picture": "images"
// }

  String? thumnail;
  String? title;
  String? subtitle;
  String? contents;
  String? picture;

  MoviesModel({
    required this.thumnail,
    required this.title,
    required this.subtitle,
    required this.contents,
    required this.picture,
  });

  MoviesModel.fromJson(Map<String, dynamic> json) {
    thumnail = json['thumnail']!.toString();
    title = json['title']!.toString();
    subtitle = json['subtitle']!.toString();
    contents = json['contents']!.toString();
    picture = json['picture']!.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['thumnail'] = thumnail;
    data['title'] = title;
    data['subtitle'] = subtitle;
    data['contents'] = contents;
    data['picture'] = picture;
    return data;
  }
}
